# update our debian/ubuntu box
alias update='sudo -- sh -c "apt update && apt upgrade -y"'
alias updateall='sudo apt update && sudo apt upgrade -y && sudo snap refresh && uv self update'
 
# make grep output colorful 
alias grep='grep --color=auto'

# git alias
alias ga='git add .'
alias gb='git branch'
alias gc='git commit -m'
alias gd='git diff'
alias gf='git fetch'
alias gl='git log --pretty=format:"%C(yellow)%h %C(cyan)%ad %Cblue%aN%C(auto)%d %Creset%s" --date=relative'
alias gp='git push'
alias gs='git status'